<?php

/**
 * Implements hook_menu().
 */
function form_alter_menu() {
  $items = array();

  $items['admin/config/people/passwords'] = array(
    'title' => 'Bad Passwords List',
    'description' => t('Configure a list of passwords that aren\'t allowed.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_alter_passwords_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'form_alter.passwords_form.inc'
  );

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function form_alter_form_alter(&$form, &$form_state, $form_id) {
  switch($form_id) {
    case 'user_profile_form':
      {
        $form['account']['pass']['#description'] = t('To change the current user password, enter the new password in both fields. Please do not use common passwords like "password", "12345", "love".');
        $form['#validate'][] = 'form_alter_validate_password';
        break;
      }
    default:
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function form_alter_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $form['account']['pass']['#description'] = t('To change the current user password, enter the new password in both fields. Please do not use common passwords like "password", "12345", "love".');
  $form['#validate'][] = 'form_alter_validate_password';
}

/**
 * Custom password validation
 */
function form_alter_validate_password($form, &$form_state) {
  // $badpasswords = array('password', '12345', 'love');
  $badpasswords = variable_get('form_alter_badpasswords');
  $badpasswords_array = explode(', ', $badpasswords);

  if (in_array($form_state['values']['pass'], $badpasswords_array)) {
    form_set_error('pass', t('Please use a more secure password!'));
  }
}
