<?php

/**
 * Implements hook_menu().
 */
function db_select_demo_menu() {
  $items = array();

  $items['admin/reports/node-list'] = array(
    'title' => 'List of Nodes',
    'description' => t('A list of nodes with published status.'),
    'page callback' => 'db_select_demo_node_list',
    'access arguments' => array('administer content')
  );

  return $items;
}

/*
 * Custom page callback for admin/reports/node-list
 */
function db_select_demo_node_list() {
  $node_types = node_type_get_types();
  $statuses = array(0, 1); // 0 = unpublished, 1 = published

  foreach($node_types as $type) {
    $typename = $type->type;

    foreach ($statuses as $status) {
      //SELECT COUNT FROM node WHERE type = $typename AND status = $status
      $query = db_select('node', 'n') //table node, alias n
        ->condition('type', $typename)
        ->condition('status', $status);

      $query->addExpression('COUNT (nid)', 'node_count'); // expression, custom label

      $results = $query->execute();
      $data = $results->fetchObject();

      if ($status == 0) {
        $status = 'unpublished';
      } else {
        $status = 'published';
      }

      $items[] = t('The %type content type has %num %status nodes.', array('%type'=>$typename, '%num'=>$data->node_count, '%status'=>$status));
    }
  }

  $content['node-list'] = array(
    '#items' => $items,
    '#theme' => 'item_list'
  );

  return render($content);
}
