<?php
/**
 * Implements hook_menu().
 */
function menu_magic_menu() {
  $items = array();

  $items['magic'] = array( // mysite.com/magic
    'title' => 'A little magic', // drupal will handle translating automatically, so no t() needed
    'page callback' => 'menu_magic_basic', // php function that will be called when accessing the page
    // 'access callback' => 'user_access', // permissions function callback. default value is 'user_access'
    'access arguments' => array('access content') // user_access('access content')
  );

  $items['magic/%'] = array( // % is a wildcard character
    'title' => 'Even more magical',
    'page callback' => 'menu_magic_extra',
    'page arguments' => array(1), // position of % in url
    'access arguments' => array('access content'),
    'file' => 'menu_magic.extra.inc' // page callback will be found in this file
  );

  $items['user/%/magic'] = array(
    'title' => 'Magic',
    'description' => 'Magical magic for users',
    'page callback' => 'menu_magic_user_tab',
    'page arguments' => array(1),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'file' => 'menu_magic.user.inc',
    'type' => MENU_LOCAL_TASK
  );

  $items['node/%node/magic'] = array( // %node is an autoloader (node_load(%)). works with any function something_load(). node_load(), user_load(), etc.
    'title' => 'Magic',
    'description' => 'Do amazing and magical things',
    'page callback' => 'menu_magic_node_context',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'menu_magic.context.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE
  );

  return $items;
}

// function menu_magic_basic() {
//   $content = array();

//   // This is a very, very simple page element. It will appear on the page,
//   // but other modules can't customize it and themes can't override its markup.
//   // keys without '#' are considered elements. keys starting with '#' are considered properties.
//   $content['raw_markup'] = array(
//     '#type' => 'markup',
//     '#markup' => '<p>Truly, this is magical!</p>'
//   );

//   return $content;
// }

function menu_magic_basic() {
  $content = array();

  // This is a very, very simple page element. It will appear on the page,
  // but other modules can't customize it and themes can't override its markup.
  // keys without '#' are considered elements. keys starting with '#' are considered properties.
  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => '<p>Truly, this is magical!</p>',
    '#prefix' => '<p>',
    '#suffix' => '</p>'
  );

  $catPicture = array(
    'path' => 'http://placekitten.com/440/400',
    'alt' => t('This is a magicla kitten'),
    'title' => t('This is the title')
  );

  $content['themed_data'] = array(
    '#type' => 'markup',
    '#markup' => theme('image', $catPicture),
    '#prefix' => '<div class="menu-magic-image">',
    '#suffix' => '</div>',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'menu_magic') . '/menu_magic.css'
      )
    )
  );

  $content['renderable_element'] = array(
    '#theme' => 'item_list',
    '#title' => t('How do we know it\'s magic?'),
    '#items' => array(
      t('Is it made of wood?'),
      t('Does it sink in water?'),
      t('Does it weigh the same as a duck?'),
      t('The current time is %time.', array('%time' => date('r')))
    ),
    '#cache' => array(
      'keys' => array('menu_magic', 'renderable_element'), // menu_magic:renderable_element
      'bin' => 'cache',
      'expire' => time() + 30,
      'granularity' => DRUPAL_CACHE_PER_PAGE //see hook_block_info function doc
    )
  );

  return $content;
}
